#!/bin/bash
set -e

if [ "${DEBUG}" = true ]; then
  set -x
fi

DEF_MYSQL_HOST=
DEF_MYSQL_PORT=3306
DEF_MYSQL_DATABASE=temp
DEF_MYSQL_USERNAME=mysql
DEF_MYSQL_PASSWORD=mysql

MYSQL_HOST=${MYSQL_HOST:-$DEF_MYSQL_HOST}
MYSQL_PORT=${MYSQL_PORT:-$DEF_MYSQL_PORT}
MYSQL_DATABASE=${MYSQL_DATABASE:-$DEF_MYSQL_DATABASE}
MYSQL_USERNAME=${MYSQL_USERNAME:-$DEF_MYSQL_USERNAME}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-$DEF_MYSQL_PASSWORD}

exec /usr/bin/mysql -h ${MYSQL_HOST} -P ${MYSQL_PORT} -u${MYSQL_USERNAME} -p${MYSQL_PASSWORD} -D ${MYSQL_DATABASE} "$@"